kind: CroneJob
apiVersion: batch/v1
metadata:
  name: minute-backup
  namespace: nginx
spec:
  schedule: "*/2 * * * *"  #runs every 2 minutes
  jobTemplate:
    spec: 
      template:
        metadata:
          name: minute-backup
          labels:
            app: minute-backup

      spec:
        containers: 
          - name: backup-container
            image: busybox
            command:
          - sh
          - -c 
          - >
            echo "backup started"
            mkdir -p /backups &&
            mkdir -p /data &&
            cp -r /demo-data /backups &&
            echo "Backup Completed";
          volumeMounts:
            - name: data-volume
              mountPath: /demo-data
            - name: backup-volume
              mountPath: /backups
          restartPolicy: Onfailure
          volumes:
            - name: data-volume
              hostPath:
                path: /demo-data
                type: DirectoryOrCreate
            - name: backup-volume
              hostPath:
                path: /backups
                type: DirectoryOrCreate
            
