kind: Job
apiVersion: batch/v1
metadata: 
  name: yukta-job
  namespace: yuktaNamespace
specs:
  completions: 1
  parallelism: 1
  template:
    metadata: 
      name: demo-job-pod
      labels:
        app: batch-task
    specs:
      container: 
        - name: batch-container
          image: busybox:latest
          command: ["sh","-c", "echo Hello, I'm Yukta Thakur && sleep 10"]
      restartPolicy: Never
      
  
