kind: StatefulSet
apiVersion: app/v1
metadata:
   name: mysql-statefulset
   namespace: mysql
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: mysql
  templates:
    metadata: 
      labels:
        app: mysql
    specs:
     containers:
     - name: mysql
       image: mysql:8.0
       ports:
       - containerPorts: 3306
       livenessProbe:
         hhtpGet:
           path: /
           port: 3306
           
       resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
       env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom: 
           secretKeyRef:
             name: mysql-secret
             key: MYSQL_ROOT_PASSWORD
             
       - name: MYSQL_DATABASE
         valueFrom:
           configMapKeyRef:
             name: mysql-config-map
             key: MYSQL_DATABASE
      volumeMounts:
        - name: mysql-data
          mountPath: /usr/share/nginx/html
      
 volumeClaimTemplates:
 - metadata:
     name: mysql-data
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 1Gi
